::-------------------------------------------------------------------------------
:: this file EOL must be Windows-EOL for the '!NL!' multiline-trick to work.
::-------------------------------------------------------------------------------

::@echo off
chcp 65001 1>nul 2>nul

setlocal enableDelayedExpansion
::------------------------------- do not remove the next empty-line, the ^ escapes the end-of-line characters.
set CRLF=^

::------------------------------- 

set "TARGET=run.ini"

set "CONTENT="

set "CONTENT=%CONTENT%!CRLF!;;;-------------file generated by '_build_run.ini.cmd', it's easier to edit."
set "CONTENT=%CONTENT%!CRLF!"
set "CONTENT=%CONTENT%!CRLF![Information]"
set "CONTENT=%CONTENT%!CRLF!"
set "CONTENT=%CONTENT%!CRLF!Parent_Folder=%~sdp0application"
set "CONTENT=%CONTENT%!CRLF!"
set "CONTENT=%CONTENT%!CRLF!Full_Path=%~sdp0application\chrome.exe"
set "CONTENT=%CONTENT%!CRLF!"

::an "easier to edit" collection of arguments (will be one long line).
::------- you can no longer use '"' characters to wrap around a whole argument.

set "CONTENT=%CONTENT%!CRLF!Arguments="
::----------------------------------------------------------------
set CONTENT=%CONTENT% --flag-switches-begin

::----------------------------------------------------------------------------- profile
set "CONTENT=%CONTENT% "--user-data-dir=%~sdp0profile"

::----------------------------------------------------------------
set "CONTENT=%CONTENT% --flag-switches-end"



Arguments=--flag-switches-begin "--user-data-dir=D:\Software\Chromium\new\profile" --force-device-scale-factor="1.25" --force-ui-direction=ltr --allow-outdated-plugins --disable-logging --disable-breakpad --disable-crash-reporter --crash-server-url="https://0.0.0.0/" --no-pings  --ignore-certificate-errors --force-color-profile="srgb" --enable-quic  --disable-features="AutomaticTabDiscarding,D3DVsync,NetworkService,NetworkServiceInProcess,SafeSearchUrlReporting,OmniboxUIExperimentHideSteadyStateUrlSchemeAndSubdomains,OmniboxUIExperimentHideSteadyStateUrlTrivialSubdomains,OmniboxUIExperimentHideSteadyStateUrlPathQueryAndRef,OmniboxUIExperimentHideSteadyStateUrlScheme,ExtensionsToolbarMenu,SafeSearchUrlReporting,ChromeLabs,ConversionMeasurement,ReadLater,ScrollableTabStrip,TabSearch,AppBanners,ClipboardContentSetting,ExperimentalAppBanners,MaterialDesignBookmarks,MaterialDesignExtensions,SecondaryUiMd,SimplifyHttpsIndicator" --enable-features="StaleWhileRevalidate,StaleWhileRevalidate2,NoStatePrefetch,SpeculativePreconnect,ParallelDownloading,BackForwardCache:TimeToLiveInBackForwardCacheInSeconds/300/should_ignore_blocklists/true/enable_same_site/true,HttpFormWarning,IncreaseInputAudioBufferSize,MarkHttpAs,brotli-encoding,AutofillShowTypePredictions,AutofillTokenPrefixMatching" --enable-stale-while-revalidate --enable-offline-load-stale-cache --autoplay-policy=document-user-activation-required --default-tile-height=128 --default-tile-width=128 --blink-settings="disallowFetchForDocWrittenScriptsInMainFrame=false" --use-simple-cache-backend=on --save-previous-document-resources=onload --enable-smooth-scrolling --ignore-autocomplete-off-autofill --blink-settings="disallowFetchForDocWrittenScriptsInMainFrame=false" --flag-switches-end





set "FILE_TARGET=run.ini"

pushd "%~sdp0"

if exist "%FILE_TARGET%" ( 
  ren "%FILE_TARGET%" "%FILE_TARGET%.old" 
) 

echo.[Information] 1>"%FILE_TARGET%"
echo.Parent_Folder=%~sdp0application 1>"%FILE_TARGET%"


[Information]
Parent_Folder=D:\Software\Chromium\new\application

Full_Path=D:\Software\Chromium\new\application\chrome.exe

Arguments=--flag-switches-begin "--user-data-dir=D:\Software\Chromium\new\profile" --force-device-scale-factor="1.25" --force-ui-direction=ltr --allow-outdated-plugins --disable-logging --disable-breakpad --disable-crash-reporter --crash-server-url="https://0.0.0.0/" --no-pings  --ignore-certificate-errors --force-color-profile="srgb" --enable-quic  --disable-features="AutomaticTabDiscarding,D3DVsync,NetworkService,NetworkServiceInProcess,SafeSearchUrlReporting,OmniboxUIExperimentHideSteadyStateUrlSchemeAndSubdomains,OmniboxUIExperimentHideSteadyStateUrlTrivialSubdomains,OmniboxUIExperimentHideSteadyStateUrlPathQueryAndRef,OmniboxUIExperimentHideSteadyStateUrlScheme,ExtensionsToolbarMenu,SafeSearchUrlReporting,ChromeLabs,ConversionMeasurement,ReadLater,ScrollableTabStrip,TabSearch,AppBanners,ClipboardContentSetting,ExperimentalAppBanners,MaterialDesignBookmarks,MaterialDesignExtensions,SecondaryUiMd,SimplifyHttpsIndicator" --enable-features="StaleWhileRevalidate,StaleWhileRevalidate2,NoStatePrefetch,SpeculativePreconnect,ParallelDownloading,BackForwardCache:TimeToLiveInBackForwardCacheInSeconds/300/should_ignore_blocklists/true/enable_same_site/true,HttpFormWarning,IncreaseInputAudioBufferSize,MarkHttpAs,brotli-encoding,AutofillShowTypePredictions,AutofillTokenPrefixMatching" --enable-stale-while-revalidate --enable-offline-load-stale-cache --autoplay-policy=document-user-activation-required --default-tile-height=128 --default-tile-width=128 --blink-settings="disallowFetchForDocWrittenScriptsInMainFrame=false" --use-simple-cache-backend=on --save-previous-document-resources=onload --enable-smooth-scrolling --ignore-autocomplete-off-autofill --blink-settings="disallowFetchForDocWrittenScriptsInMainFrame=false" --flag-switches-end


;Arguments=--flag-switches-begin "--user-data-dir=D:\Software\Chromium\new\profile" --no-default-browser-check --ignore-autocomplete-off-autofill --allow-outdated-plugins --disable-logging --disable-breakpad --disable-crash-reporter --crash-server-url="https://0.0.0.0/" --no-pings --force-device-scale-factor="1.25" --ignore-certificate-errors --force-color-profile="srgb" --disable-features="OmniboxUIExperimentHideSteadyStateUrlSchemeAndSubdomains,OmniboxUIExperimentHideSteadyStateUrlTrivialSubdomains,OmniboxUIExperimentHideSteadyStateUrlPathQueryAndRef,OmniboxUIExperimentHideSteadyStateUrlScheme,ExtensionsToolbarMenu,SafeSearchUrlReporting" --enable-features="ParallelDownloading,OmniboxUIExperimentShowSuggestionFavicons" --flag-switches-end

;;;--disable-stale-while-revalidate --disable-offline-load-stale-cache --disable-features="StaleWhileRevalidate2"
;;; --enable-stale-while-revalidate  --enable-offline-load-stale-cache  --enable-features="StaleWhileRevalidate2"
;;;--enable-fast-unload
;;;--user-agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4284.0 Safari/537.36" --disable-canvas-aa --disable-2d-canvas-clip-aa --webgl-antialiasing-mode=none --disable-composited-antialiasing --ppapi-antialiased-text-enabled=0 --ppapi-subpixel-rendering-setting=0 --disable-font-subpixel-positioning --autoplay-policy=document-user-activation-required --default-tile-height=128 --default-tile-width=128 --num-raster-threads=4
;;;BackForwardCache:TimeToLiveInBackForwardCacheInSeconds/300/should_ignore_blocklists/true/enable_same_site/true

Run_Mode=SW_SHOWMAXIMIZED
